---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_host_key_checking: false
    ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 600



    - name: "install python for Ansible."
      apt:
        name: python3
        state: latest
        update_cache: yes
      # Your code here

  environment:
    - NODE_ENV=production
    - VERSION=1
    - TYPEORM_CONNECTION=postgres
    - TYPEORM_MIGRATIONS_DIR=./src/migrations
    - TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
    - TYPEORM_MIGRATIONS=./src/migrations/*.ts
    - TYPEORM_HOST=postgres.cmwfpjybtjbl.us-west-2.rds.amazonaws.com
    - TYPEORM_PORT=5432
    - TYPEORM_USERNAME=postgres
    - TYPEORM_PASSWORD='#Eliz13919'
    - TYPEORM_DATABASE=postgres
  roles:
    - configure-server
    - configure-prometheus-node-exporter