---
- name: 'update and upgrade packages.'
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
- name: 'remove unneedded deps'
  become: true
  apt:
    autoremove: yes
- name: "Install Node.js 13"
  shell: |
    # Install Node.js LTS version as our base Node.js version
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt-get install -y nodejs

    # Use n version manager to switch to Node.js v13.8.0
    sudo npm install -g n
    sudo n 13.8.0


- name: 'install pm2'
  become: true
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

- name: 'create abckend app dir'
  file: 
    path: ~/backend_app_dir
    state: directory


- name: 'Copy artifact to instance'
  become: true
  unarchive:
    src: files/artifact.tar.gz
    dest: ~/backend_app_dir


- name: start app
  become: true
  shell: |
    tar artifact.tar.gz
    npm install
    npm run build
    pm2 stop all
    pm2 start npm -- start

